apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.api }}
  labels:
    {{- include "pariksha.labels" . | nindent 4 }}
    name: {{ .Values.namespaces.api }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.web }}
  labels:
    {{- include "pariksha.labels" . | nindent 4 }}
    name: {{ .Values.namespaces.web }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.workers }}
  labels:
    {{- include "pariksha.labels" . | nindent 4 }}
    name: {{ .Values.namespaces.workers }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.fabric }}
  labels:
    {{- include "pariksha.labels" . | nindent 4 }}
    name: {{ .Values.namespaces.fabric }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.data }}
  labels:
    {{- include "pariksha.labels" . | nindent 4 }}
    name: {{ .Values.namespaces.data }}
