apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pariksha.serviceAccountName" (dict "Release" .Release "saName" .Values.questionService.serviceAccount.name) }}
  namespace: {{ .Values.namespaces.api }}
  labels:
    {{- include "pariksha.componentLabels" (dict "Chart" .Chart "Release" .Release "component" "question-service") | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.questionService.serviceAccount.gcpServiceAccount }}
