apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pariksha.serviceAccountName" (dict "Release" .Release "saName" .Values.candidatePortal.serviceAccount.name) }}
  namespace: {{ .Values.namespaces.web }}
  labels:
    {{- include "pariksha.componentLabels" (dict "Chart" .Chart "Release" .Release "component" "candidate-portal") | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.candidatePortal.serviceAccount.gcpServiceAccount }}
