apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pariksha.serviceAccountName" (dict "Release" .Release "saName" .Values.cryptoLifecycle.serviceAccount.name) }}
  namespace: {{ .Values.namespaces.api }}
  labels:
    {{- include "pariksha.componentLabels" (dict "Chart" .Chart "Release" .Release "component" "crypto-lifecycle") | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.cryptoLifecycle.serviceAccount.gcpServiceAccount }}
