global:
  environment: prod

apiGateway:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 1Gi
  hpa:
    minReplicas: 3
    maxReplicas: 15
    targetCPUUtilization: 65

questionService:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 1Gi
  hpa:
    minReplicas: 3
    maxReplicas: 15
    targetCPUUtilization: 65

paperGenerator:
  replicas: 3
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 4000m
      memory: 2Gi
  hpa:
    minReplicas: 3
    maxReplicas: 30
    targetCPUUtilization: 50

cryptoLifecycle:
  replicas: 3
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 4000m
      memory: 2Gi

examSessionService:
  replicas: 3
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 4000m
      memory: 2Gi
  hpa:
    minReplicas: 3
    maxReplicas: 30
    targetCPUUtilization: 60

collusionEngine:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 1Gi

blockchainService:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 1Gi

adminDashboard:
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  hpa:
    minReplicas: 3
    maxReplicas: 10

candidatePortal:
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  hpa:
    minReplicas: 3
    maxReplicas: 50
    targetCPUUtilization: 60

workers:
  irtCalibrator:
    replicas: 2
    resources:
      requests:
        cpu: 4000m
        memory: 8Gi
      limits:
        cpu: 8000m
        memory: 16Gi
    hpa:
      minReplicas: 2
      maxReplicas: 10
  matrixSolver:
    replicas: 2
    resources:
      requests:
        cpu: 4000m
        memory: 8Gi
      limits:
        cpu: 8000m
        memory: 16Gi
    hpa:
      minReplicas: 2
      maxReplicas: 10
  collusionDetector:
    replicas: 2
    resources:
      requests:
        cpu: 4000m
        memory: 8Gi
      limits:
        cpu: 8000m
        memory: 16Gi
    hpa:
      minReplicas: 2
      maxReplicas: 10
  tlpGenerator:
    replicas: 2
    resources:
      requests:
        cpu: 4000m
        memory: 8Gi
      limits:
        cpu: 8000m
        memory: 16Gi
    hpa:
      minReplicas: 2
      maxReplicas: 10
  scoreEquator:
    replicas: 2
    resources:
      requests:
        cpu: 4000m
        memory: 8Gi
      limits:
        cpu: 8000m
        memory: 16Gi
    hpa:
      minReplicas: 2
      maxReplicas: 10

fabric:
  persistence:
    storageClass: premium-rwo
    peerSize: 50Gi
    ordererSize: 20Gi
    couchdbSize: 50Gi
